### ISSUE TITLE
Precision of map$addCircle when lat and long are stored as numeric.

### ISSUE THREAD

**Issue by johnpauls** [jcheng5/leaflet-shiny#13]
Hello,
Thanks for making this (and shiny). I had an issue when I used the `map$addCircle()` function. I had stored my Lat and Long data as numeric, with 7 digits after the decimal point. When I plotted the data on a mapbox map, the centers of the circles were off ~50 meters. However, when I first used `as.character()` on the coordinates, the error went away.

**Comment by dholstius** [comment]
Same problem with `map$addPolygon()`. 

Might be the same issue as https://github.com/ramnathv/rCharts/issues/248 . Sounds like `RJSONIO::toJSON()` keeps only 2 digits by default.

EDIT: @johnpauls Can you paste example? Wrapping in `as.character()` doesn't seem to fix it for me.

**Comment by johnpauls** [comment]
With shiny 0.10.1, which  increased the precision of the data sent to JSON,  this issue is resolved
