### ISSUE TITLE
 What is the difference to other leaflet-R packages?

### ISSUE THREAD

**Issue by Make42** [jcheng5/leaflet-shiny#21]
There exist (at least) two other R-packages for leaflet:

https://github.com/rstudio
https://github.com/chgrl/leafletR

What is the difference to this package, and when and why should I use which one?

**Comment by lifan0127** [comment]
This package allows to "integrate and control Leaflet maps from Shiny applications" that are currently not supported by the RStudio version yet. I don't have experience with leafletR.

**Comment by Make42** [comment]
Thank you for your answer! I just got a reply from @jcheng5, saying that the RStudio version does support shiny by now. However, jcheng5's version can't do without shiny.
He answered here: https://github.com/rstudio/leaflet/issues/47#issuecomment-85847876
